import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "@/components/ui/app-sidebar/app-sidebar";
import { SidebarProvider } from "@/components/shadcn/sidebar";
import { AppContent } from "@/components/layout/app-content/app-content";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen`}>
        <SidebarProvider>
          <AppSidebar />
          <AppContent>{children}</AppContent>
        </SidebarProvider>
      </body>
    </html>
  );
}
