name: Build and Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: TurboRepo Remote Cache Server
        uses: trappar/turborepo-remote-cache-gh-action@v1
