name: CI with Remote Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Cache
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 및 pnpm 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      # 3. 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # 4. Remote Cache 복원 (Artifacts 다운로드)
      - name: Download Turbo Remote Cache
        uses: actions/download-artifact@v4
        with:
          name: turbo-cache
          path: .turbo

      # 5. Turbo 빌드 실행
      - name: Run Turbo Build
        run: pnpm turbo build

      # 6. Remote Cache 저장 (Artifacts 업로드)
      - name: Upload Turbo Remote Cache
        uses: actions/upload-artifact@v4
        with:
          name: turbo-cache
          path: .turbo
